<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'students' => array(   
				'course' => array(   
					'parent-table' => 'courses',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'regno',
					'child-primary-key-index' => 0,
					'tab-label' => 'Students',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/group.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(0 => 'Regno', 1 => 'Name', 2 => 'Course', 3 => 'Year of study', 4 => 'Academicyear'),
					'display-field-names' => array(0 => 'regno', 1 => 'name', 2 => 'course', 3 => 'year', 4 => 'academicyear'),
					'sortable-fields' => array(0 => '`students`.`regno`', 1 => '`students`.`name`', 2 => '`students`.`course`', 3 => '`students`.`year`', 4 => '`students`.`academicyear`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-students',
					'template-printable' => 'children-students-printable',
					'query' => "SELECT `students`.`regno` as 'regno', `students`.`name` as 'name', IF(    CHAR_LENGTH(`courses1`.`name`), CONCAT_WS('',   `courses1`.`name`), '') as 'course', `students`.`year` as 'year', IF(    CHAR_LENGTH(`academic_year1`.`name`), CONCAT_WS('',   `academic_year1`.`name`), '') as 'academicyear' FROM `students` LEFT JOIN `courses` as courses1 ON `courses1`.`id`=`students`.`course` LEFT JOIN `academic_year` as academic_year1 ON `academic_year1`.`id`=`students`.`academicyear` "
				),
				'academicyear' => array(   
					'parent-table' => 'academic_year',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'regno',
					'child-primary-key-index' => 0,
					'tab-label' => 'Students',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/group.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(0 => 'Regno', 1 => 'Name', 2 => 'Course', 3 => 'Year of study', 4 => 'Academicyear'),
					'display-field-names' => array(0 => 'regno', 1 => 'name', 2 => 'course', 3 => 'year', 4 => 'academicyear'),
					'sortable-fields' => array(0 => '`students`.`regno`', 1 => '`students`.`name`', 2 => '`students`.`course`', 3 => '`students`.`year`', 4 => '`students`.`academicyear`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-students',
					'template-printable' => 'children-students-printable',
					'query' => "SELECT `students`.`regno` as 'regno', `students`.`name` as 'name', IF(    CHAR_LENGTH(`courses1`.`name`), CONCAT_WS('',   `courses1`.`name`), '') as 'course', `students`.`year` as 'year', IF(    CHAR_LENGTH(`academic_year1`.`name`), CONCAT_WS('',   `academic_year1`.`name`), '') as 'academicyear' FROM `students` LEFT JOIN `courses` as courses1 ON `courses1`.`id`=`students`.`course` LEFT JOIN `academic_year` as academic_year1 ON `academic_year1`.`id`=`students`.`academicyear` "
				)
			),
			'units' => array(   
			),
			'courses' => array(   
			),
			'attendance' => array(   
				'student' => array(   
					'parent-table' => 'students',
					'parent-primary-key' => 'regno',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 6,
					'tab-label' => 'Attendance Record',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/application_view_icons.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(0 => 'Student', 1 => 'Regno', 2 => 'Week', 3 => 'Date', 4 => 'Unit', 5 => 'Attended', 7 => 'Semester', 8 => 'Academicyear'),
					'display-field-names' => array(0 => 'student', 1 => 'regno', 2 => 'week', 3 => 'date', 4 => 'unit', 5 => 'attended', 7 => 'semester', 8 => 'academicyear'),
					'sortable-fields' => array(0 => '`attendance`.`student`', 1 => '`attendance`.`regno`', 2 => '`attendance`.`week`', 3 => '`attendance`.`date`', 4 => '`attendance`.`unit`', 5 => '`attendance`.`attended`', 6 => '`attendance`.`id`', 7 => '`attendance`.`semester`', 8 => '`attendance`.`academicyear`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-attendance',
					'template-printable' => 'children-attendance-printable',
					'query' => "SELECT IF(    CHAR_LENGTH(`students1`.`name`), CONCAT_WS('',   `students1`.`name`), '') as 'student', IF(    CHAR_LENGTH(`students1`.`regno`), CONCAT_WS('',   `students1`.`regno`), '') as 'regno', `attendance`.`week` as 'week', if(`attendance`.`date`,date_format(`attendance`.`date`,'%m/%d/%Y'),'') as 'date', IF(    CHAR_LENGTH(`units1`.`name`), CONCAT_WS('',   `units1`.`name`), '') as 'unit', concat('<img src=\"', if(`attendance`.`attended`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />') as 'attended', `attendance`.`id` as 'id', `attendance`.`semester` as 'semester', IF(    CHAR_LENGTH(`academic_year1`.`name`), CONCAT_WS('',   `academic_year1`.`name`), '') as 'academicyear' FROM `attendance` LEFT JOIN `students` as students1 ON `students1`.`regno`=`attendance`.`student` LEFT JOIN `units` as units1 ON `units1`.`id`=`attendance`.`unit` LEFT JOIN `academic_year` as academic_year1 ON `academic_year1`.`id`=`students1`.`academicyear` "
				),
				'unit' => array(   
					'parent-table' => 'units',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 6,
					'tab-label' => 'Attendance Record',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/application_view_icons.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(0 => 'Student', 1 => 'Regno', 2 => 'Week', 3 => 'Date', 4 => 'Unit', 5 => 'Attended', 7 => 'Semester', 8 => 'Academicyear'),
					'display-field-names' => array(0 => 'student', 1 => 'regno', 2 => 'week', 3 => 'date', 4 => 'unit', 5 => 'attended', 7 => 'semester', 8 => 'academicyear'),
					'sortable-fields' => array(0 => '`attendance`.`student`', 1 => '`attendance`.`regno`', 2 => '`attendance`.`week`', 3 => '`attendance`.`date`', 4 => '`attendance`.`unit`', 5 => '`attendance`.`attended`', 6 => '`attendance`.`id`', 7 => '`attendance`.`semester`', 8 => '`attendance`.`academicyear`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-attendance',
					'template-printable' => 'children-attendance-printable',
					'query' => "SELECT IF(    CHAR_LENGTH(`students1`.`name`), CONCAT_WS('',   `students1`.`name`), '') as 'student', IF(    CHAR_LENGTH(`students1`.`regno`), CONCAT_WS('',   `students1`.`regno`), '') as 'regno', `attendance`.`week` as 'week', if(`attendance`.`date`,date_format(`attendance`.`date`,'%m/%d/%Y'),'') as 'date', IF(    CHAR_LENGTH(`units1`.`name`), CONCAT_WS('',   `units1`.`name`), '') as 'unit', concat('<img src=\"', if(`attendance`.`attended`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />') as 'attended', `attendance`.`id` as 'id', `attendance`.`semester` as 'semester', IF(    CHAR_LENGTH(`academic_year1`.`name`), CONCAT_WS('',   `academic_year1`.`name`), '') as 'academicyear' FROM `attendance` LEFT JOIN `students` as students1 ON `students1`.`regno`=`attendance`.`student` LEFT JOIN `units` as units1 ON `units1`.`id`=`attendance`.`unit` LEFT JOIN `academic_year` as academic_year1 ON `academic_year1`.`id`=`students1`.`academicyear` "
				)
			),
			'Marks' => array(   
				'unit' => array(   
					'parent-table' => 'units',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Marks',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/chart_line_add.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Name', 2 => 'Unit', 3 => 'Student', 4 => 'Regno', 5 => 'Year', 6 => 'Marks', 7 => 'Grade', 8 => 'Academicyear', 9 => 'Semester', 10 => 'Date'),
					'display-field-names' => array(1 => 'name', 2 => 'unit', 3 => 'student', 4 => 'regno', 5 => 'year', 6 => 'marks', 7 => 'grade', 8 => 'academicyear', 9 => 'semester', 10 => 'date'),
					'sortable-fields' => array(0 => '`Marks`.`id`', 1 => '`Marks`.`name`', 2 => '`Marks`.`unit`', 3 => '`Marks`.`student`', 4 => '`Marks`.`regno`', 5 => '`Marks`.`year`', 6 => '`Marks`.`marks`', 7 => '`Marks`.`grade`', 8 => '`Marks`.`academicyear`', 9 => '`Marks`.`semester`', 10 => '`Marks`.`date`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-Marks',
					'template-printable' => 'children-Marks-printable',
					'query' => "SELECT `Marks`.`id` as 'id', `Marks`.`name` as 'name', IF(    CHAR_LENGTH(`units1`.`name`), CONCAT_WS('',   `units1`.`name`), '') as 'unit', IF(    CHAR_LENGTH(`students1`.`name`), CONCAT_WS('',   `students1`.`name`), '') as 'student', IF(    CHAR_LENGTH(`students1`.`regno`), CONCAT_WS('',   `students1`.`regno`), '') as 'regno', IF(    CHAR_LENGTH(`students1`.`year`), CONCAT_WS('',   `students1`.`year`), '') as 'year', `Marks`.`marks` as 'marks', `Marks`.`grade` as 'grade', IF(    CHAR_LENGTH(`academic_year1`.`name`), CONCAT_WS('',   `academic_year1`.`name`), '') as 'academicyear', `Marks`.`semester` as 'semester', if(`Marks`.`date`,date_format(`Marks`.`date`,'%m/%d/%Y'),'') as 'date' FROM `Marks` LEFT JOIN `units` as units1 ON `units1`.`id`=`Marks`.`unit` LEFT JOIN `students` as students1 ON `students1`.`regno`=`Marks`.`student` LEFT JOIN `academic_year` as academic_year1 ON `academic_year1`.`id`=`students1`.`academicyear` "
				),
				'student' => array(   
					'parent-table' => 'students',
					'parent-primary-key' => 'regno',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Marks',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/chart_line_add.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Name', 2 => 'Unit', 3 => 'Student', 4 => 'Regno', 5 => 'Year', 6 => 'Marks', 7 => 'Grade', 8 => 'Academicyear', 9 => 'Semester', 10 => 'Date'),
					'display-field-names' => array(1 => 'name', 2 => 'unit', 3 => 'student', 4 => 'regno', 5 => 'year', 6 => 'marks', 7 => 'grade', 8 => 'academicyear', 9 => 'semester', 10 => 'date'),
					'sortable-fields' => array(0 => '`Marks`.`id`', 1 => '`Marks`.`name`', 2 => '`Marks`.`unit`', 3 => '`Marks`.`student`', 4 => '`Marks`.`regno`', 5 => '`Marks`.`year`', 6 => '`Marks`.`marks`', 7 => '`Marks`.`grade`', 8 => '`Marks`.`academicyear`', 9 => '`Marks`.`semester`', 10 => '`Marks`.`date`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-Marks',
					'template-printable' => 'children-Marks-printable',
					'query' => "SELECT `Marks`.`id` as 'id', `Marks`.`name` as 'name', IF(    CHAR_LENGTH(`units1`.`name`), CONCAT_WS('',   `units1`.`name`), '') as 'unit', IF(    CHAR_LENGTH(`students1`.`name`), CONCAT_WS('',   `students1`.`name`), '') as 'student', IF(    CHAR_LENGTH(`students1`.`regno`), CONCAT_WS('',   `students1`.`regno`), '') as 'regno', IF(    CHAR_LENGTH(`students1`.`year`), CONCAT_WS('',   `students1`.`year`), '') as 'year', `Marks`.`marks` as 'marks', `Marks`.`grade` as 'grade', IF(    CHAR_LENGTH(`academic_year1`.`name`), CONCAT_WS('',   `academic_year1`.`name`), '') as 'academicyear', `Marks`.`semester` as 'semester', if(`Marks`.`date`,date_format(`Marks`.`date`,'%m/%d/%Y'),'') as 'date' FROM `Marks` LEFT JOIN `units` as units1 ON `units1`.`id`=`Marks`.`unit` LEFT JOIN `students` as students1 ON `students1`.`regno`=`Marks`.`student` LEFT JOIN `academic_year` as academic_year1 ON `academic_year1`.`id`=`students1`.`academicyear` "
				)
			),
			'academic_year' => array(   
			)
		);

	/*************************************/
	/* End of configuration */


	$currDir = dirname(__FILE__);
	include("{$currDir}/defaultLang.php");
	include("{$currDir}/language.php");
	include("{$currDir}/lib.php");
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags($_REQUEST['SelectedID']);
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children', 'get-records-printable', 'show-children-printable'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li%s><a href="#panel_%s-%s" id="tab_%s-%s" data-toggle="tab">%s%s</a></li>' . "\n\t\t\t\t\t",($tabLabels ? '' : ' class="active"'), $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="tab-pane%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? '' : ' active'), $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<button type="button" class="btn btn-default" data-target="#panel_%s-%s" id="tab_%s-%s" data-toggle="collapse">%s %s</button>' . "\n\t\t\t\t\t", $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="collapse"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records-printable" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable'){
				$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy] ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable'){
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template-printable'], $data);
			}else{
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
